### ISSUE TITLE
Function Get-ClickUpViewTasks

### ISSUE THREAD

**Issue by StefanM224** [DrDrrae/ClickUpPowerShell#10]
This is incorrectly $Views.views when it should be $Views.tasks.

Views.ps1 line 193

```
    $Views = Invoke-ClickUpAPIGet -Arguments $QueryString -Endpoint "view/$ViewID/task"
    Return $Views.views
```

**Comment by DrDrrae** [comment]
Thanks. I'll get this fixed.

**Comment by StefanM224** [comment]
Forgot to mention function Get-ClickUpViewTasks is actually misspelled as Get-ClickUpViewTaks - I think I fixed it on my computer but wanted to mention it! Love this module I appreciate your hard work on this!
